### PR TITLE
Added new quick start screencast

### PR DESCRIPTION
**Pull request by ghost**
This adds the new quick start screencast discussed in https://github.com/lervag/vimtex/issues/1946.

### CODE REVIEW

**Comment by lervag** [comment]
Do you propose adding the quick-start as an mp4 in the README? I've not seen many github READMEs that use mp4s as the animation format. Before I merge this I want to understand if there are any major pros/cons that should be weighted.

**Comment by lervag** [comment]
I'm trying to find some reference or similar that describes the current supported file formats.

**Comment by lervag** [comment]
https://stackoverflow.com/a/4279746/51634

**Comment by lervag** [comment]
So, it seems mp4s are now generally supported, but I still want to find the proper documentation reference. The only reference I can find is [this](https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/file-attachments-on-issues-and-pull-requests).

**Comment by ghost** [comment]
This seems to be a new feature, so perhaps that is why there is little documentation available? I found this related blog post: https://github.blog/2021-05-13-video-uploads-available-github/, which is from 10 days ago.

**Comment by lervag** [comment]
Great, thanks. I'll merge this for now and push an initial update to the README file now.

**Pull request merged**
